### ISSUE TITLE
Auto-focus on first input

### ISSUE THREAD

**Issue by castaf** [Pylons/deform#249]
It's annoying, when there are some contents above the form, to have an auto-focus on the first input of the form, because the page scroll down to this input automaticaly on load and the content above become invisible. Could we think about a parameter which allowes to deactivate this behavior, or maybe remove the call to focusFirstInput() ?

**Comment by miohtama** [comment]
I *think* this is fixed because I have been using Deform 2.0 on production on mobile sites without issues.

**Comment by tisdall** [comment]
@miohtama - I'm pretty sure this is still an issue as [deform.js still has a focusFirstInput call](https://github.com/Pylons/deform/blob/master/deform/static/scripts/deform.js#L29)

The issue only comes up if you put a form "below the fold".  It causes the screen to scroll down to the first field.  The major problem is there's no way to disable this feature as it's permanently turned on.

**Comment by j23d** [comment]
Just run into this with a form at the bottom of the page and had to overwrite [focusFirstInput](https://github.com/Pylons/deform/blob/master/deform/static/scripts/deform.js#L159) to get rid it. I think it would be better to activate the behavior only on purpose, like explained above.

**Comment by stevepiercy** [comment]
This issue is now resolved by #365, and will be released in Deform 3.0.0.
